---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: local-shared-volume
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: "{{ vol_size }}Gi"
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "{{ mnt_path }}"
