---
- name: "download flannel-network configuration"
  get_url:
    url: https://raw.githubusercontent.com/coreos/flannel/v0.9.1/Documentation/kube-flannel.yml
    dest: /tmp/flannel.yml

- name: "extract primary interface"
  shell: ifconfig | grep -o -m1 -E '(eth|ens|en)[[:digit:]]'
  register: primary_interface_check
  changed_when: False

- name: "register interface"
  set_fact:
    primary_interface: "{{ primary_interface_check.stdout }}"
  when: primary_interface_check is succeeded

- name: "update flannel-network configuration"
  replace:
    path: /tmp/flannel.yml
    regexp: '(flanneld)(.[^]]+)'
    replace: '\1\2, "--iface={{ primary_interface }}"'
  when: primary_interface_check is succeeded

- name: "install flannel-network"
  command: kubectl apply -f /tmp/flannel.yml